### ISSUE TITLE
Repository pour ajout simplifié sur Android

### ISSUE THREAD

**Issue by khyinn** [f-lawe/plugin.video.orange.fr#20]
Bonjour,

Est-il possible de créer un repo pour pouvoir installer le plugin sans avoir à envoyer le fichier sur Android ? En effet, c'est un peu compliqué sur Android TV de mettre des fichiers sur la box TV pour effectuer l'installation. L'utilisation d'un repo serait plus simple.

**Comment by BreizhReloaded** [comment]
Salut @khyinn !
C'est dans la feuille de route 2022, j'aimerais bien le publier sur le dépôt principal de Kodi. Je garde cette discussion ouverte en attendant que ça soit fait.

**Comment by f-lawe** [comment]
C'est proposé à Kodi, j'espère que ça va arriver d'ici peu !

**Comment by f-lawe** [comment]
Ca y est, c'est dispo ! Je clôture ce point.
