### ISSUE TITLE
Récupération droits compte Orange

### ISSUE THREAD

**Issue by tpimont** [f-lawe/plugin.video.orange.fr#22]
Bonjour,

Est il possible de prévoir une option dans le plugin pour pouvoir mettre son compte Orange ?
Les chaines disponibles de base se limitent à la TNT en gros, l'idéal serait de pouvoir récupérer les droits sur les chaines incluses avec son compte Orange.

Merci d'avance de la réponse sur la faisabilité ou non.
En tout cas merci pour ce plugin qui fonctionne très bien

**Comment by BreizhReloaded** [comment]
Salut @tpimont !

Si tu es derrière ta box Orange/Sosh, tu devrais avoir accès à toutes tes chaînes, de mémoire tu as les chaînes d'info étrangères genre CNN par exemple. Tu as aussi accès au chaînes payantes, ça m'a été confirmé et j'ai pu enfin le tester récemment avec BeIN.

Si tu es depuis une autre connexion, en effet, cet addon ne gère pas d'accéder à Orange via tes identifiants. Il faudrait que je regarde en détail, mais il me semble qu'il y a un captcha quand on se connecte depuis un autre opérateur, et dans ce cas ça rendrait l'opération impossible.

**Comment by BreizhReloaded** [comment]
Ok, intéressant, et plutôt bonne nouvelle.

Ça ne sera pas pour demain, mais c'est définitivement un truc à regarder pour plus tard.

**Comment by f-lawe** [comment]
J'ai pu avancer récemment sur cette question. J'ai pu reproduire le processus de connexion via un script JavaScript, que j'essaye maintenant de reproduire en Python. Donc ça a l'air faisable sur le papier, mais pour le moment je bloque sur un souci d'en-tête HTTP (je n'arrive pour le moment pas à envoyer les mêmes requêtes que mon navigateur et JavaScript avec Python).

Affaire à suivre.

**Comment by f-lawe** [comment]
Ok, ça tourne pour la télé en direct ! Le temps d'ajouter de quoi configurer ça depuis les paramètres du plugin, et ça part. Je traiterai le replay dans un second temps.

**Comment by f-lawe** [comment]
Et hop, c'est envoyé, je clôture le sujet. J'envoie ça sur le dépôt de Kodi prochainement.
