### ISSUE TITLE
pas d'EPG / info sur orange Caraibes

### ISSUE THREAD

**Issue by elkir0** [f-lawe/plugin.video.orange.fr#25]
Les flux videos sont OK mais tout ce qui est EPG là par contre ça ne veut rien.
la ligne EPG sur simple iptv client reste vide, surement un probleme de ce coté là.
en tout cas un travail dingue ce plugin, 👍🏼

**Comment by BreizhReloaded** [comment]
Un peu tardivement, je vais regarder ça ! Il y a un truc qui a sauté aussi en métropole (les images des chaînes n'apparaissent plus), donc sûrement une mise à jour du côté d'Orange.

Affaire à suivre.

**Comment by starmate** [comment]
Bonjour,

J’ai le même problème pour Orange Réunion.

De mémoire, il s’agissait d’un problème que j’avais corrigé dans le code sur mon android tv. C’était lié aux images manquantes.

J’avais fait une condition if dans le code pour ne pas charger l’image si celle-ci était manquante… Si va peut aider…

**Comment by BreizhReloaded** [comment]
Bonjour à tous !
J'ai été vraiment beaucoup pris ces derniers mois, je suis désolé. Mais les vacances de Noël arrivent, je suis preneur de ton bout de code @starmate pour l'intégrer !
