### ISSUE TITLE
Plus de logo des chaines

### ISSUE THREAD

**Issue by Bestdoud** [f-lawe/plugin.video.orange.fr#27]
Les logo des chaines ont disparus

**Comment by CoderReloaded** [comment]
Orange a ajouté un marqueur dans l'url des logos des chaînes. j'ai codé un fix rapide qui fonctionne.

`    def get_streams(self) -> list:
        req = Request(self.endpoint_streams, headers={
            'User-Agent': random_ua(),
            'Host': urlparse(self.endpoint_streams).netloc
        })

        with urlopen(req) as res:
            channels = json.loads(res.read())

        streams = []

        for channel in channels:
            channel_id: str = channel['id']

            #Fix maqueur url
            logo = channel['logos']['square'] if 'square' in channel['logos'] else None
            marker = logo.find('%2F')
            channel_logo = logo[:marker]+logo[marker+3:].replace('/','%2F')

            streams.append({
                'id': channel_id,
                'name': channel['name'],
                'preset': channel['zappingNumber'],
                'logo': channel_logo,
                'stream': f'plugin://plugin.video.orange.fr/channel/{channel_id}',
                'group': [group_name for group_name in self.groups if int(channel['id']) in self.groups[group_name]]
            })`

**Comment by CoderReloaded** [comment]
Orange a ajouté un marqueur dans l'url des logos. J'ai fait un fix dans la méthode get_streams du fichier orange.py

`    def get_streams(self) -> list:
        req = Request(self.endpoint_streams, headers={
            'User-Agent': random_ua(),
            'Host': urlparse(self.endpoint_streams).netloc
        })

        with urlopen(req) as res:
            channels = json.loads(res.read())

        streams = []

        for channel in channels:
            channel_id: str = channel['id']

            logo = channel['logos']['square'] if 'square' in channel['logos'] else None
            marker = logo.find('%2F')
            channel_logo = logo[:marker]+logo[marker+3:].replace('/','%2F')

            streams.append({
                'id': channel_id,
                'name': channel['name'],
                'preset': channel['zappingNumber'],
                'logo': channel_logo,
                'stream': f'plugin://plugin.video.orange.fr/channel/{channel_id}',
                'group': [group_name for group_name in self.groups if int(channel['id']) in self.groups[group_name]]
            })`

**Comment by CoderReloaded** [comment]
Orange a ajouté un marqueur dans l'url des logos. J'ai fait un fix dans la méthode get_streams du fichier orange.py

`for channel in channels:
            channel_id: str = channel['id']

            logo = channel['logos']['square'] if 'square' in channel['logos'] else None
            marker = logo.find('%2F')
            channel_logo = logo[:marker]+logo[marker+3:].replace('/','%2F')

            streams.append({
                'id': channel_id,
                'name': channel['name'],
                'preset': channel['zappingNumber'],
                'logo': channel_logo,
                'stream': f'plugin://plugin.video.orange.fr/channel/{channel_id}',
                'group': [group_name for group_name in self.groups if int(channel['id']) in self.groups[group_name]]
            })`

**Comment by CoderReloaded** [comment]
Orange a ajouté un marqueur dans l'url des logos. J'ai fait un fix dans la méthode get_streams du fichier orange.py

`
for channel in channels:
            channel_id: str = channel['id']

            logo = channel['logos']['square'] if 'square' in channel['logos'] else None
            marker = logo.find('%2F')
            channel_logo = logo[:marker]+logo[marker+3:].replace('/','%2F')

            streams.append({
                'id': channel_id,
                'name': channel['name'],
                'preset': channel['zappingNumber'],
                'logo': channel_logo,
                'stream': f'plugin://plugin.video.orange.fr/channel/{channel_id}',
                'group': [group_name for group_name in self.groups if int(channel['id']) in self.groups[group_name]]
            })

`

**Comment by CoderReloaded** [comment]
Orange a ajouté un marqueur dans l'url des logos. J'ai modifié la méthode get_streams du fichier orange.fr

`

        for channel in channels:
            channel_id: str = channel['id']
            logo = channel['logos']['square'] if 'square' in channel['logos'] else None
            marker = logo.find('%2F')
            channel_logo = logo[:marker]+logo[marker+3:].replace('/','%2F')

            streams.append({
                'id': channel_id,
                'name': channel['name'],
                'preset': channel['zappingNumber'],
                'logo': channel_logo,
                'stream': f'plugin://plugin.video.orange.fr/channel/{channel_id}',
                'group': [group_name for group_name in self.groups if int(channel['id']) in self.groups[group_name]]
            })`

**Comment by Bestdoud** [comment]
Bonjour,
super d'avoir trouvé et corrigé le problème
ou met-on ce morceau de code dans le fichier orange.py ? directement à la fin ?

**Comment by Floooowk** [comment]
Bonjour,

J'ai essayé la technique de @CoderReloaded et updaté le fichier orange.py (en enlevant la petite guillemet à la fin), puis recompressé l'archive et réinstallé l'extension modifiée.
J'arrive à installer l'application, mais elle ne fonctionne plus : juste après l'installation elle m'afficher "Erreur de Orange TV France". 

F.

**Comment by CoderReloaded** [comment]
Désolé, j'ai proposé une modif à @BreizhReloaded dans son repo. je pense qu'il faudra attendre pour le fichier d'install et voir si il n'y a pas une méthode plus propre pour faire cette bidouille.

Cette modif pour moi fonctionne, mais je n'ai pas eu besoin de réinstallé l'addon, j'ai directement modifié le fichier dans le répertoire de l'addon dans Kodi déjà installé. Ensuite j'ai rafraichi les chaines et le guide dans ipTvManager et cela à fonctionné.

L'url retourné par l'endpoint est
`https://proxymedia.woopic.com/api/v1/images/553%2F/logos/v2/logos/livetv_tf1/20180417_164011/webTVSquare/logo_150x150.png`

alors que la bonne url devrait-être
`https://proxymedia.woopic.com/api/v1/images/553%2Flogos%2Fv2%2Flogos%2Flivetv_tf1%2F20180417_164011%2FwebTVSquare%2Flogo_150x150.png`

Voilà ce que fait mon bout de code, mais jen ne garantit pas qu'il fonctionne de facoon optimale pour tout le monde. Je laisse @BreizhReloaded voir si il n'y a pas une facon plus fonctionnel.

**Comment by CoderReloaded** [comment]
PS: Le copier/coller de ma solution dans mon commentaire précédent peut entrainer des erreurs si il est mal fait. Python respecte une certaine indentation pour que le code soit fonctionnel. Si vous n'avez pas de connaissance de ce language, il peut être compliqué de debug le problème. D'ici la, il est préférable d'attendre une intégration de cette modification, proprement dans l'addon par le propriétaire de celui-ci.

**Comment by Floooowk** [comment]
Bonjour @CoderReloaded un grand merci pour ces précisions :)
Effectivement, je ne connais pas du tout le Python, donc je vais plutôt sagement attendre une version à jour de l'add-on.

D'ailleurs, à cet effet, est-ce qu'il existe un repo pour avoir une mise à jour automatique de l'add-on ? Ou faut-il télécharger à chaque fois le ZIP et surveiller les MAJ ?

**Comment by Bestdoud** [comment]
je pense avoir réussi. voici le zip
[plugin.video.orange.fr.zip](https://github.com/BreizhReloaded/plugin.video.orange.fr/files/9854162/plugin.video.orange.fr.zip)

**Comment by Floooowk** [comment]
Merci beaucoup @Bestdoud ! Cela fonctionne pour moi !
