### ISSUE TITLE
Super addon Mais difficile à installer

### ISSUE THREAD

**Issue by sitronet** [f-lawe/plugin.video.orange.fr#29]
Félicitation pour cet addon.
Mais quelle galère pour le configurer afin que cela fonctionne.
En autre, je me suis aperçu que la dépendance PySock ne s'installe pas automatiquement, j'ai dû faire l'installation à part.
Sinon super

**Comment by f-lawe** [comment]
Je suis en train de regarder pour une disponibilité sur les plugins disponibles sur Kodi par défaut. A suivre :)
