### ISSUE TITLE
Problème actualisation automatique des chaines 

### ISSUE THREAD

**Issue by Dragon548** [f-lawe/plugin.video.orange.fr#31]
Bonjour, 
J'ai un soucis avec ce plugin depuis que j'ai changé de box android. 
Je l'utilisais avant sur une box Xiaomi et tout fonctionnais correctement. 
Or depuis que je suis passé sur Chromecast TV j'ai un soucis d'actualisation : je suis obligé d'actualiser manuellement les chaines 1 fois par jour depuis les options du plugin (cf photo jointe en fin de message). 
Sinon la liste des chaines reste vide dans l'onglet TV. 
C'est assez pénible... Quelqu'un aurait il une idée pour régler ce problème ? 
Merci par avance pour votre aide :) 

https://ibb.co/DDwXKzK

**Comment by f-lawe** [comment]
Salut @Dragon548 !

Le plugin vient d'être mis à jour, pour ne supporter maintenant plus que l'intégration via IPTV Manager. Si tu as encore des soucis par la suite, c'est sûrement de leur côté (ce plugin ne renvoie des informations que quand IPTV Manager le demande).
