### ISSUE TITLE
Plus de guide

### ISSUE THREAD

**Issue by Bestdoud** [f-lawe/plugin.video.orange.fr#32]
Depuis quelques jours le guide ne fonctionne plus
J'ai un message d'erreur orange qui apparaît
Ils ont sûrement du changer quelque chose

**Comment by theoden11** [comment]
Bonjour. En effet depuis le 6 juin exactement le guide ne fonctionne plus. Personnellement j'ai dû faire de la grosse bidouille pour  arriver à avoir de nouveau un guide, en travaillant sur les paramètres du client PVR IPTV et en empêchant le plugin de modifier le guide : le modèle de création de l'EPG n'est pas totalement compatible avec un autre guide (donc des modifs de code). Sans ces bidouilles régulièrement le guide est vidé... Par conséquent je ne peux donner de "tuto", c'est trop compliqué et trop aléatoire. Idéalement il faut retourner sous CaptchupTV&More, qui marche plutôt bien, sauf certaines chaines, et qui présente un guide et un replay.

**Comment by bobix88** [comment]
meme constat, donc j'ai modifié les paramètre dans les configs iptv manager pour mettre dans guide l'url https://xmltvfr.fr/xmltv/xmltv_tnt.xml
Pour l'instant, ca fonctionne...

**Comment by theoden11** [comment]
Oui, plusieurs url de guide sont possibles. Mais en théorie il devrait y avoir des chaines vides de guide, car les noms des chaines du plugin orange ne correspondent pas toutes aux noms des chaines dans les autres grabbers. (NRJ 12, BFM TV, RMC Dévouverte par ex)

**Comment by f-lawe** [comment]
Corrigé dans les versions 2.x :)
