### ISSUE TITLE
Kodi nexus support

### ISSUE THREAD

**Issue by pasnox** [f-lawe/plugin.video.orange.fr#34]
je viens de migrer a kodi Nexus, et il me dit qu'il n'y a pas de version disponible pour cette extension. possible de corriger ?

Merci

**Comment by AnthonyL29** [comment]
J'ai downgradé hier de Nexus vers Matrix pour pouvoir faire l'installation.
Aujourd'hui, Kodi est repassé en version Nexus (je pensais avoir désactivé les MàJ auto...) et ça fonctionne tout de même correctement.

**Comment by f-lawe** [comment]
Les versions 2.x sont disponibles pour Nexus et Omega, j'ai publié des versions en test si ça vous intéresse !

**Comment by pasnox** [comment]
Je ne suis malheureusement plus utilisateur orange.

**Comment by f-lawe** [comment]
Ahah, c'est noté. Je clos la discussion alors.
