### ISSUE TITLE
Semble ne plus fonctionner 

### ISSUE THREAD

**Issue by yo97490** [f-lawe/plugin.video.orange.fr#35]
Bonjour 

les chaines tv semblent ne plus fonctionner. J'ai désintaller et réinstaller l'extension mais aucune chaine n'apparait avec petit message "erreur d'orange tv france". 
Si quelqu'un est dans la meme situation.

**Comment by nico2che** [comment]
J'ai le même soucis a l'instant, je cherche les logs

**Comment by Bestdoud** [comment]
Moi aussi
J'ai bien les images et le guide mais plus de vidéo
Ils ont eu encore changer quelque chose

**Comment by Enniota** [comment]
same

**Comment by Enniota** [comment]
je ne comprend pas comment obtenir les log mais en gros , quand iptv manager va cherche les chaine ca met une erreur

**Comment by Pacapac** [comment]
Même problème. La playlist m3u doit ne plus fonctionner peut être. Je n'ai pas de solution

**Comment by Bestdoud** [comment]
Il faut surement modifier les liens suivant dans le fichier orange.py

endpoint_stream_info = 'https://mediation-tv.orange.fr/all/live/v3/applications/PC/users/me/channels/{channel_id}/stream?terminalModel=WEB_PC',
 
endpoint_streams = 'https://mediation-tv.orange.fr/all/live/v3/applications/PC/channels?mco=OFR',
 
endpoint_programs = 'https://rp-ott-mediation-tv.woopic.com/api-gw/live/v3/applications/PC/programs?period={period}&mco=OFR',

**Comment by bobix88** [comment]
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
Ca ressemble bien à un pb de endpoint, oui.

**Comment by Bestdoud** [comment]
Le problème semble résolu
surement un problème temporaire chez Orange

**Comment by yo97490** [comment]
> Le problème semble résolu
> 
> surement un problème temporaire chez Orange

Effectivement tout semble rentré dans l'ordre

**Comment by yo97490** [comment]
Ne fonctionne plus à nouveau 😔

**Comment by Bestdoud** [comment]
Idem ça dit que la chaîne ne fait pas partie de mon abonnement (registration)
J'espère que c'est un problème orange et que ça va vite se résoudre
Mais bon ça commence à beaucoup déconner
Je sent qu'un jour ça ne fonctionnera plus du tout

**Comment by yo97490** [comment]
Tout ça pour nous pousser à prendre des abonnements avec leur décodeur 💸

**Comment by Enniota** [comment]
ca semble fonctionee par intermitance

**Comment by Bestdoud** [comment]
En attendant, j'ai remis catchup TV & more depuis le dépôt branche bêta de catchuptv qui semble bien fonctionner, à voir dans le temps. Et il y a quelques chaînes en plus
Faut juste avoir des comptes sur les divers sites de replay TF1, M6, BFMRMC et utiliser kodi 20 version stable. J'avais mis la 21 mais France 4 et 5 faisaient planter

**Comment by Pacapac** [comment]
Bonjour, ça ne fonctionne plus. Un message apparaît : ce programme ne fait pas partie de votre abonnement.
En ce qui concerne catch up TV, France 2 ne fonctionne pas, cela fait que saccader.

**Comment by Bestdoud** [comment]
Je n ai pas ce problème
Utilise tu la version 0.2.39 bêta 39 ?

**Comment by redref** [comment]
J'ai regardé pour récupérer la fonctionnalité, mais je suis bloqué sur le nouveau système d'auth.

Il s'agit d'une combinaison entre un token envoyé en Header tv_token et un Cookie nommé wassup que je ne sais pas interprété.

**Comment by maskimfr** [comment]
Bonjour,

J'ai réussi à le faire fonctionner de nouveau.
J'utilise cet addon avec mon abonnement mobile, et cela des modification modifications pour l'authentification.

Mais je pense que la modification suivante pourrai résoudre le problème:

Dans le fichier resources/lib/providers/fr/orange.py, remplacer :

`endpoint_stream_info` = `'https://mediation-tv.orange.fr/all/live/v3/applications/PC/users/me/channels/{channel_id}/stream?terminalModel=WEB_PC',`

par :
`endpoint_stream_info` = 'https://mediation-tv.orange.fr/all/api-gw/live/v3/auth/accountToken/applications/PC/channels/{channel_id}/stream?terminalModel=WEB_PC',`

Je n'ai plus d'abonnement fibre orange, donc je ne peux pas tester.

**Comment by Pacapac** [comment]
Salut, tu as modifier le fichier orange.py sur ton tel ? Car pour moi l'authentification par token peut se faire s'il y a une gestion préalable de connexion. Ce qui n'est pas le cas avec l'addon orange tv de kodi

**Comment by Bestdoud** [comment]
Je viens de tester et ça ne fonctionne pas non plus. L'addon s'installe bien mais j'ai une erreur juste après l'installation

**Comment by maskimfr** [comment]
Orange vient de rajouter une authentification (Tv_token) en plus de changer une des URL. Peut-être qu'il le faut aussi depuis une connexion Orange/Sosh.
Avant je n'avais besoin que du cookie pour avoir les chaines depuis n'importe quelle connexion.

Si vous souhaitez utiliser ma version: https://github.com/maskimfr/plugin.video.orange.fr/archive/refs/heads/master.zip

Attention, il est nécessaire d'ajouter les cookies et le token d'authentification (Tv_token) dans le fichier `resources/lib/provider_templates/orange.py`

Pour les obtenir, il est nécessaire de se connecter au site https://chaines-tv.orange.fr avec un navigateur (chrome ou dérivé, j'ai eu un soucis avec Firefox qui tronquait les cookies lors de mes tests avec l'inspection). Il faut lancer la lecture d'une chaine pour avoir le token Tv_token.

Je n'ai pas testé tous les cas de figure, notamment l'initialisation sans aucune données importées (j'avais déjà les chaines importées quand j'ai fait la modification). Il est possible que ça ne fonctionne pas. Dans ce cas je regarderai demain ou ce week-end.
Autre point, je n'ai pas vérifié la durée de validité du token, donc il est possible que ça ne marche que quelques heures. Les cookies sont valides plusieurs mois (voire 1 an ? ), donc pas de soucis de ce côté.

Je pourrai regarder pour faire une version plus simple à configurer s'il y a des personnes interessées.

**Comment by yo97490** [comment]
> Orange vient de rajouter une authentification (Tv_token) en plus de changer une des URL. Peut-être qu'il le faut aussi depuis une connexion Orange/Sosh.
> 
> Avant je n'avais besoin que du cookie pour avoir les chaines depuis n'importe quelle connexion.
> 
> 
> 
> Si vous souhaitez utiliser ma version: https://github.com/maskimfr/plugin.video.orange.fr/archive/refs/heads/master.zip
> 
> 
> 
> Attention, il est nécessaire d'ajouter les cookies et le token d'authentification (Tv_token) dans le fichier `resources/lib/provider_templates/orange.py`
> 
> 
> 
> Pour les obtenir, il est nécessaire de se connecter au site https://chaines-tv.orange.fr avec un navigateur (chrome ou dérivé, j'ai eu un soucis avec Firefox qui tronquait les cookies lors de mes tests avec l'inspection). Il faut lancer la lecture d'une chaine pour avoir le token Tv_token.
> 
> 
> 
> Je n'ai pas testé tous les cas de figure, notamment l'initialisation sans aucune données importées (j'avais déjà les chaines importées quand j'ai fait la modification). Il est possible que ça ne fonctionne pas. Dans ce cas je regarderai demain ou ce week-end.
> 
> Autre point, je n'ai pas vérifié la durée de validité du token, donc il est possible que ça ne marche que quelques heures. Les cookies sont valides plusieurs mois (voire 1 an ? ), donc pas de soucis de ce côté.
> 
> 
> 
> Je pourrai regarder pour faire une version plus simple à configurer s'il y a des personnes interessées.
> 
> 
> 
> 

Je tente de faire la manip mais ne voit pas où trouver le tv_t'oient et le cookie

**Comment by remzouille** [comment]
Cette version marche-t-elle pour vous ?
[https://github.com/remzouille/plugin.video.orange.fr](https://github.com/remzouille/plugin.video.orange.fr)

**Comment by Bestdoud** [comment]
ne marche pas chez moi

**Comment by leoberry** [comment]
Fonctionne chez moi : 
- Nvidia Shield
- Kodi on Android TV
- Mise à jour de l'addon, restart de kodi. 
Premier affichage un peu long, le temps de récupérer le cookie et le header

**Comment by RhAbder** [comment]
> Cette version marche-t-elle pour vous ? https://github.com/remzouille/plugin.video.orange.fr

ca marche désormais très bien chez moi avec cette version, un grand merci 🙏🏻
Kodi v19 sur Chromecast Android TV

**Comment by Pacapac** [comment]
> Cette version marche-t-elle pour vous ? https://github.com/remzouille/plugin.video.orange.fr

Un grand merci, cela fonctionne bien, Kodi v 20.2. 
La modification apporté fait remarcher le pluggin :)

**Comment by Bestdoud** [comment]
Mince alors y a que chez moi que ça ne fonctionne plus 🤔

**Comment by remzouille** [comment]
Je viens de publier une nouvelle version plus "respectueuse", que je vous recommande d'utiliser.

Elle ne régénère le couple cookie / token qu'en cas de besoin alors que la précédente le faisait systématiquement après 30 minutes.

Pourriez-vous poster ici le résultat des lignes "Orange TV France: cookie/token invalide, âge = ..." présentes dans le log ? Ça nous donnera une idée sur la durée de validité du couple cookie / token.

@Bestdoud : peux-tu préciser un peu ? Pour quels OS / version de Kodi ça marche ou pas ? Le log pourrait aussi être utile.

**Comment by redref** [comment]
@remzouille , we should also use Auth for the get_streams part.

```
$ curl https://mediation-tv.orange.fr/all/api-gw/live/v3/auth/accountToken/applications/PC/channels?mco=OFR
{"code":40,"message":"Missing credentials","description":"Token d'authentification ou header de contrôle manquant","status":401}
```

**Comment by Bestdoud** [comment]
Ne fonctionne pas sur Amazon firetv stick 4k et lite avec kodi 20.2 version armv7
Et sur Windows 10
Kodi version 20.2 
J'ai pas accès aux log pour le moment

**Comment by redref** [comment]
On my side, got an issue with get_streams part, where a 504 error was raised.

Switched to the program URL grouped by channel (like the webpage) but need to work a bit on Logos.

Working with this fork (in PR) on Matric, gonna test nexus soon : #36

**Comment by redref** [comment]
License server can also return 401/403.

Needs a fix to refresh token on this occasion.

**Comment by Bestdoud** [comment]
ta version @redref fonctionne chez moi
manque plus que les logo

**Comment by remzouille** [comment]
Je pense que ça ne fonctionne pas sur certaines machines car tu n'as peut-être pas le fichier userdata/addon_data/plugin.video.orange.fr/cache/streams.json, utilisé par défaut quand la fonction get_streams échoue.
Si quelqu'un pouvait le poster ici ça serait sympa.
J'ai posté un PR pour une solution fonctionnelle, à condition d'avoir ce fichier, mais il y a encore un peu de travail pour récupérer la liste des chaînes avec les noms corrects et les logos.

**Comment by Bestdoud** [comment]
Je l'ai dans mon pc sous windows

[streams.json](https://github.com/BreizhReloaded/plugin.video.orange.fr/files/13249217/streams.json)

**Comment by remzouille** [comment]
C'est celui généré par la fonction get_streams de @redref, il faudrait la version précédente, générée avant les modifications par Orange. Je pourrai le poster ici mais pas avant dimanche car je ne l'ai plus sur ma machine.

**Comment by remzouille** [comment]
Le dernier commit que je viens de faire résout le problème des chaînes et des logos, voir PR #37.

**Comment by Bestdoud** [comment]
je n'arrive pas à faire fonctionner ta version
Iptv manager génère un erreur dès le début du refresh
quand je remet la version  @redref ça fonctionne hormis les icones
voici mon log si ça peut aider
[kodi.zip](https://github.com/BreizhReloaded/plugin.video.orange.fr/files/13257386/kodi.zip)

**Comment by remzouille** [comment]
Un fichier n'avait pas été uploadé, tu peux me dire si ça marche maintenant ?

**Comment by Bestdoud** [comment]
Ca fonctionne bravo

**Comment by Bestdoud** [comment]
Par contre j'ai toujours des icones avec le logo oranges dans les groupes de chaines. je n'arrive pas à faire afficher autre chose même en effaçant tout
C'est pas grave mais s'il y a une solution je suis preneur car ça pique un peu les yeux
![icones orange](https://github.com/BreizhReloaded/plugin.video.orange.fr/assets/58991927/994820c1-ab1c-4363-bb9f-82c9a7570fb1)

**Comment by yo97490** [comment]
> Cette version marche-t-elle pour vous ?
> 
> [https://github.com/remzouille/plugin.video.orange.fr](https://github.com/remzouille/plugin.video.orange.fr)

Je confirme fonctionne à nouveau. Merci. Manque plus l'affichage des programmes.

**Comment by Bestdoud** [comment]
Pour ma part, Je n'ai pas ce problème, j'ai bien le guide et les programmes s'affichent bien quand je visionne une chaine

**Comment by yo97490** [comment]
> Pour ma part, Je n'ai pas ce problème, j'ai bien le guide et les programmes s'affichent bien quand je visionne une chaine

J'ai du rater quelque chose 😟

**Comment by Bestdoud** [comment]
Moi avec catchup j'avais UNKNOW en haut à gauche
Et en dessous le titre de l'épisode
Et avec ce plugin ça met bien le nom du programme/série en cours et en dessous le titre de l'épisode

**Comment by Enniota** [comment]
Je dois utiliser quelle version ?

**Comment by Enniota** [comment]
De kodi

**Comment by Enniota** [comment]
Ca marche mais je n'ai pas le guide

**Comment by Enniota** [comment]
Fonctionnent correctement apres 2h désole du derangement

**Comment by Enniota** [comment]
marche mais quand ca veux

**Comment by Enniota** [comment]
ne marche pas tout le temp de temp en temp ca ne marche juste pas je peut meme pas refresh les chaine

**Comment by remzouille** [comment]
Prends la dernière version

**Comment by Jeanrange** [comment]
Bonjour,

Je me suis inscrit pour savoir comment on fait pour récupérer le fork fonctionnelle.

Vaut-il mieux attendre un peu ?

Merci

**Comment by Bestdoud** [comment]
C'est pas évident
Il faut être en version pc pour afficher un bouton code vert
Dedans il faut choisir télécharger zip
Sinon je me suis fait un lien
https://github.com/BreizhReloaded/plugin.video.orange.fr/files/13257620/plugin.video.orange.fr-OK1123.zip

**Comment by remzouille** [comment]
Voici un lien direct vers mon fork.
[https://github.com/remzouille/plugin.video.orange.fr/archive/refs/heads/master.zip](https://github.com/remzouille/plugin.video.orange.fr/archive/refs/heads/master.zip)
Il est maintenant pleinement fonctionnel, la liste des chaînes et les logos sont récupérés depuis la page d'accueil.
J'ai aussi activé l'option inputstream.adaptive.play_timeshift_buffer qui permet de mettre en pause la vidéo. Je ne l'ai pas encore beaucoup testé, ça marche très bien sur mon ordinateur mais pas sur ma clé Xiaomi TV Stick 4K, probablement par manque de stockage. Par contre impossible pour l'instant d'avancer dans le flux qui a été enregistré.

**Comment by Jeanrange** [comment]
Cool, merci bcp

**Comment by Bestdoud** [comment]
Est ce la même version que celle qu tu m'avais fait tester il y a quelques jours ?

**Comment by remzouille** [comment]
Non, la liste des chaînes et des logos n'est plus codée en dur mais téléchargée.
Par contre, j'ai l'impression que l'option inputstream.adaptive.play_timeshift_buffer ne sert pas pour pouvoir mettre en pause.

**Comment by Bestdoud** [comment]
S'il n'y a pas eu d'erreur c'est bon signe
Par contre c'est sûrement que iptv simple n'a pas bien été paramétré par iptv manager
Il faut aller dans paramètres
Puis gestionnaire de fichiers
Puis dossier du profil
Puis Addon data
Puis pvr.iptvsimple
Effacer les 2 fichiers setting
Aller dans les paramètres de iptvmanager
Dans l'onglet iptv simple, configurer automatiquement iptv simple
Puis refaire la mise à jour des chaînes

Il est aussi possible de faire
Dans les paramètres enregistreur TV
Onglet général
Effacer les données
Prendre la deuxième ligne et valider
Ça va recharger les chaînes de suite


Il faut aussi peut être démarrer pour relancer les plugins

**Comment by therapeat** [comment]
> S'il n'y a pas eu d'erreur c'est bon signe Par contre c'est sûrement que iptv simple n'a pas bien été paramétré par iptv manager Il faut aller dans paramètres Puis gestionnaire de fichiers Puis dossier du profil Puis Addon data Puis pvr.iptvsimple Effacer les 2 fichiers setting Aller dans les paramètres de iptvmanager Dans l'onglet iptv simple, configurer automatiquement iptv simple Puis refaire la mise à jour des chaînes Tu peux vérifier dans les paramètres de iptv simple si ça c'est bien mis en chemin local Si c'est pas le cas c'est que iptvmanager a pas paramétré iptv simple
> 
> Il est aussi possible de faire Dans les paramètres enregistreur TV Onglet général Effacer les données Prendre la deuxième ligne et valider Ça va recharger les chaînes de suite
> 
> Il faut aussi peut être redémarrer Kodi pour relancer les plugins

Je te remercie. J’ai fais la manipulation plusieurs fois de configuration automatique et même si ça me marquait que ça allait supprimer le fichier ça ne fonctionnait pas.

Au final ça fonctionne. Mais je ne sais toujours pas d’où venait le problème. Deux solutions possibles:
- La configuration auto ne supprimait pas réellement le premier fichier.
- J’ai redémarré kodi en quittant (chose que j’avais faite) mais surtout en forçant l’arrêt et visant le cache sous android tv. Et au démarrage suivant tout s’est activé. (Je suppose que ceci était la solution).

Néanmoins je te remercie pour ton aide, grâce à ton intervention tout fonctionne de nouveau. Chaînes, guides, logos tout est là.

bonne soirée à tous.

**Comment by slanglade** [comment]
Je confirme : avec la dernière version master en date + suppression de la config pvr.iptvsimple avec l'explorateur de fichier intégré à kodi + reconfig iptv simple depuis iptv manager + rafraîchir les canaux, ça remarche !

J'ai pas mal galéré pour remettre le truc en fonction, j'avais l'impression d'avoir déjà fait ça (et desinstallé / réinstallé les plugins concernés  et viré le cache et sacrifié des animaux), mais en suivant cette méthode d'un bloc et sans rien redémarré,  bim ça marche.

**Comment by Pacapac** [comment]
Bonsoir, je ne sais pas pour vous, mais ça ne marche à nouveau plus chez moi. Lors du fetching des chaînes ça plante. Merci de votre aide

**Comment by Bestdoud** [comment]
Je viens d'essayer et ça se met bien à jour

**Comment by Pacapac** [comment]
Pourrais tu me dire comment je peux faire pour me dépanner, ça me met Erreur orange tv france Consulter le journal pour plus d'information. Mais je ne sais pas où récupérer ces journaux

**Comment by Bestdoud** [comment]
As tu bien pris la dernière version de remzouille ici ?

https://github.com/remzouille/plugin.video.orange.fr/archive/refs/heads/master.zip
Et penser a redémarrer Kodi après installation

**Comment by Pacapac** [comment]
J'ai réinstaller la version que tu m'a donner dans le lien précédent. Cependant, après avoir activer l'intégration iptv manager et basique dans les option du pluggin orange tv, lorsque je configuré iptvsimple client automatically, puis que je fais un refresh des channels, ca met un temps fou et, ça ne marche pas. À la fin j'ai rien dans l'onglet TV de kodi. Pas de guide et pas de chaînes. Même après plusieurs effacement des fichiers settings dans le dossier du profil add-on data, iptvmanager. Saurais tu comment faire ? J'ai redémarrer plusieurs fois kodi entre temps. Mais pareil. On dirait que le pluggin fonctionne, mais pas le dialogue entre iptvmanager et iptvsimple client

**Comment by Pacapac** [comment]
Bon finalement j'y suis parvenu en spammant le bouton configurer iptv simple client dans iptv manager lol. Merci en tout cas car je n'avais pas la bonne version du pluggin ! Bonne soirée.

**Comment by bruduju** [comment]
Merci pour la MàJ. Quelqu'un connait-il un equivalent pour Emby ?

**Comment by Pacapac** [comment]
Bonjour, cela fonctionne comme je l'ai dit précédemment. Par contre chaque matin je dois faire un refresh des chaînes. Avec un updating un peu long. Ça ne marche plus sinon. La liste des chaînes est vide dans la section tv. Est ce pareil pour vous ? Il y a t-il une solution à ce petit problème ? Ma femme n'arrive pas à mettre à jour sans mon aide lol.

**Comment by Bestdoud** [comment]
As tu essayé ceci

Dans les paramètres enregistreur TV
Onglet général
Effacer les données
Prendre la deuxième ligne et valider
Ça va recharger les chaînes de suite

Il faut aussi peut être redémarrer Kodi pour relancer les plugins

**Comment by Pacapac** [comment]
D'accord j'essayerai la prochaine fois. Cependant est ce une solution pérenne ? Ou faut il le faire à chaque fois ? Merci

**Comment by Bestdoud** [comment]
Je ne sais pas
Ça m'arrive de le faire de temps en temps

**Comment by Bestdoud** [comment]
Bonjour,
Est ce que le plugin fonctionne encore chez vous ?
La mise a jour se fait bien mais j'ai une erreur lorsque je lance une chaine

**Comment by DeepKool** [comment]
Pareil depuis ce matin.

**Comment by f-lawe** [comment]
La version [2.0.0+beta.2](https://github.com/f-lawe/plugin.video.orange.fr/releases/tag/v2.0.0%2Bbeta.2) corrige tout ça normalement !

**Comment by Bestdoud** [comment]
Bonjour, j'ai essayé la version 2 bêta 2 mais impossible de lire les flux. j'ai un message d'erreur quelque soit la chaine
j'ai remis l'ancien plugin et ça refonctionne

**Comment by f-lawe** [comment]
Oh, étrange ça. Tu arriverais à m'envoyer les logs de l'erreur ? Tu es sur Orange France, Réunion ou Caraïbe ?

**Comment by f-lawe** [comment]
Hmm... Tous les logs du côté de Orange TV France ont l'air ok. Si c'était un problème de DRM, l'erreur serait différente (j'ai pu voir ce que ça donnait en mettant à jour le plugin). Est-ce que ton InputStream Adaptive est à jour ?

Je tourne sous Omega, avec InputStream Adaptive à la version 21.4.9.

**Comment by Bestdoud** [comment]
Bien vu j'ai mis à jour kodi et ça fonctionne
J'espère que çà fonctionnera sur mon firetv aussi
merci

**Comment by f-lawe** [comment]
Oui, ça c'est très possible, les paramètres ont un peu changé. Content de valider que ça fonctionne en dehors de chez moi !

Je clôture cette discussion.
