### ISSUE TITLE
Orange Sénégal EPG ?

### ISSUE THREAD

**Issue by fredmo** [f-lawe/plugin.video.orange.fr#40]
Bonsoir,

Je suis à la recherche d'un équivalent de 
https://github.com/BreizhReloaded/plugin.video.orange.fr/blob/master/resources/lib/providers/fr/orange.py
pour le service Orange Sénégal,

Auriez vous des conseils ?

Merci

**Comment by f-lawe** [comment]
Salut @fredmo

Pour Orange France, j'ai simplement observé ce qui se passait dans mon navigateur quand je regardais la télé depuis le [site web dédié](https://chaines-tv.orange.fr/?filtres=all) (mais uniquement accessible normalement derrière une connexion Orange France). S'il y a un système similaire au Sénégal, on peut penser à mettre en place un équivalent. Encore plus si l'architecture est très proche, comme pour Orange Réunion ou Orange Caraibe (qui utilise les mêmes URL, avec seulement un paramètre qui est changé).

**Comment by f-lawe** [comment]
Je clôture parce que je n'ai pas de retour. Si d'autres personnes sont intéressées et sont motivées pour me filer un coup de main (n'étant pas au Sénégal avec une connexion Orange, je ne peux pas tester moi-même), n'hésitez pas à rouvrir cette discussion !
