### ISSUE TITLE
streamlink plugin

### ISSUE THREAD

**Issue by campones** [f-lawe/plugin.video.orange.fr#41]
hello
I was wondering if you could make a plugin to have orange  tv  working with streamlink, since you apparently solved the drm issue  involved?

Thank you

**Comment by f-lawe** [comment]
Hello @campones

The DRM thing is handled by [inputstream.adaptive](https://github.com/xbmc/inputstream.adaptive). This plugin simply emulates a web browser on the Orange web tv. It fetches DRM information and forwards it to inputstream.adaptive. This where you want to go :)
