### ISSUE TITLE
PVR manager is starting up : 0% Stuck - Solution in comment

### ISSUE THREAD

**Issue by toniohc** [f-lawe/plugin.video.orange.fr#45]
Hello. 
Fresh install of this add on following the readme on Kodi Omega with a Firestick 4k.

Once everything is setup, it stay forever on PVR Manager is starting up: 0%

Try uninstall Kodi. Clear cache and data. Reinstall only Orange Add-On with IpTV Manager and still the same issue. 
M3U Playlist URL is empty. EPG too. Don't know if it's normal. 

Edit : Same problem on Kodi Omega on Windows ( Fresh install with only plugin.video.orange.fr addon 
![image](https://github.com/f-lawe/plugin.video.orange.fr/assets/2438572/7dc7715c-44ee-4ffc-a9f9-008b8c8f1924)
![image](https://github.com/f-lawe/plugin.video.orange.fr/assets/2438572/3c69ad27-cc10-472d-978c-dccdcc0fe49a)

**Comment by toniohc** [comment]
Found this in log. Maybe it can help.

**Comment by toniohc** [comment]
I've got a : 
Failed URL using bad/illegal format or missing UR in log file and the m3u url adresse is empty on iptvsimple

**Comment by toniohc** [comment]
I do a video ( Just click on it for full installation of the plugin ).
Did i do something wrong ? 

[![Kody Omega Orange Plugin PVR Stuck 0%](https://i.ibb.co/s23QK64/Capture-d-cran-2024-06-22-205356.png)](https://www.youtube.com/watch?v=OYAx7JH_O3w "Kody Omega Orange Plugin PVR Stuck 0%")

**Comment by f-lawe** [comment]
That may be related to this issue on IPTV Manager ([#107](https://github.com/add-ons/service.iptv.manager/issues/107)). I faced the same problem, IPTV Simple PVR is not properly autoconfigured any more. We can see on your screenshots, the M3U playlist URL field is empty, so I suggest you do it manually (as I did). That should do the trick.

(on peut parler en français si tu préfères)

**Comment by toniohc** [comment]
Ok merci je vais tenter ça. 

Cette solution : 
special://userdata/addon_data/service.iptv.manager/playlist.m3u8
special://userdata/addon_data/service.iptv.manager/epg.xml 
?

**Comment by f-lawe** [comment]
Super, merci pour la solution @toniohc ! On va maintenant espérer qu'ils arrivent à réparer ça rapidement du côté de IPTV Manager.

Je clôture la discussion.

**Comment by MikeOrbita24** [comment]
Works on Omega 21.1:
Delete old and reinstall IPTV Simple Client, open its settings
Create one more new configuratrion, turn it off, set a name, put url of your cannal list from IPTV provoder, press OK
Open default configuration("Migrate add-on config") and just pul url of IPTV list, press OK
Go to the main page and press TV - manager will start loading.
