### ISSUE TITLE
variable manquant dans settings.xml

### ISSUE THREAD

**Issue by revanwolf** [f-lawe/plugin.video.orange.fr#49]
Bonjour,

Le plugin ne semble pas du tout communiquer avec IPTV Manager, j'ai testé avec la version du dépôt Kodi et la dernière version du GitHub (2.1.2) et rien ne se passe et cela sur 3 Kodi 21.0 différents (2 Android tv et un Windows).

Le seul moyen que je suis arrivé à le faire fonctionner est de mettre la version 1.5 d'activer l'option integration IPTV manager et ensuite il fonctionnera en 2.x.

Et j'ai trouvé le soucis au bout de pas mal d'heures qui est en fait ultra simple il manque une valeur dans le fichiers settings.xml en 2.0 qui est présent en 1.5.

`    <setting id="iptv.enabled">true</setting>`

J'ai fait une install propre du plugin et rajouté cette variable et le plugin marche parfaitement.

**Comment by flolmr** [comment]
je confirme!

un **grand merci** à toi pour la manip, j'étais à 2 doigts de virer le plugin
ça marche nickel pour ma part sur une mi box s, kodi 21, install fraiche du plugin dans la dernière version

(j'avais tenté auparavant la manip du settings.xml en instance-settings-1.xml, je ne sais pas si c'est le mix des 2 ou juste cette ligne supplémentaire qui fait le job)

**Comment by revanwolf** [comment]
Il faut les 2, la variable sur une installation nouvelle et le instance-settings qui est du à un changement sur IPTV client.

J'ai aussi une Mi Box S qui à de nouveau accès aux chaines TV d'Orange.

**Comment by toniohc** [comment]
> Bonjour,
> 
> Le plugin ne semble pas du tout communiquer avec IPTV Manager, j'ai testé avec la version du dépôt Kodi et la dernière version du GitHub (2.1.2) et rien ne se passe et cela sur 3 Kodi 21.0 différents (2 Android tv et un Windows).
> 
> Le seul moyen que je suis arrivé à le faire fonctionner est de mettre la version 1.5 d'activer l'option integration IPTV manager et ensuite il fonctionnera en 2.x.
> 
> Et j'ai trouvé le soucis au bout de pas mal d'heures qui est en fait ultra simple il manque une valeur dans le fichiers settings.xml en 2.0 qui est présent en 1.5.
> 
> ` <setting id="iptv.enabled">true</setting>`
> 
> J'ai fait une install propre du plugin et rajouté cette variable et le plugin marche parfaitement.

Modification effectuée à l'instant et problème résolu. Problème apparu suite à l'installation de la version Kodi. 
Merci pour ton aide.

**Comment by JeanMerand** [comment]
> Bonjour,
> 
> Le plugin ne semble pas du tout communiquer avec IPTV Manager, j'ai testé avec la version du dépôt Kodi et la dernière version du GitHub (2.1.2) et rien ne se passe et cela sur 3 Kodi 21.0 différents (2 Android tv et un Windows).
> 
> Le seul moyen que je suis arrivé à le faire fonctionner est de mettre la version 1.5 d'activer l'option integration IPTV manager et ensuite il fonctionnera en 2.x.
> 
> Et j'ai trouvé le soucis au bout de pas mal d'heures qui est en fait ultra simple il manque une valeur dans le fichiers settings.xml en 2.0 qui est présent en 1.5.
> 
> ` <setting id="iptv.enabled">true</setting>`
> 
> J'ai fait une install propre du plugin et rajouté cette variable et le plugin marche parfaitement.

Bonjour, j'utilise KODI sur mon laptop Windows 10 mais je ne trouve pas où ce situe le fichier xml que vous indiquez. Seriez-vous me dire où le trouver ?

**Comment by toniohc** [comment]
Ne fonctionne plus.

**Comment by revanwolf** [comment]
> maintenant j'ai accès aux replay mais toujours pas au live... mais j'ai peut-être mal compris ce que vous avez expliqué... est-ce que c'est ce qu'il fallait faire ?

Simplement la variable dont j'ai mentionné 

`<setting id="iptv.enabled">true</setting>`

Il y a besoin de rien d'autre.

Néanmoins le guide TV ne semble plus fonctionner, le live lui fonctionne pour le moment.

**Comment by f-lawe** [comment]
C'est intéressant, parce qu'en reprenant le développement j'avais eu quelques soucis de ce côté-là. Mais comme par la suite ça se passait bien, j'en avais conclu que c'était juste moi qui avait mal branché un truc sur mon Kodi de test. Je regarde ça en détail et j'essaye de pousser un correctif rapidement !

**Comment by f-lawe** [comment]
C'est disponible sur GitHub, j'attends vos retours pour clôturer cette discussion. Il faudra attendre un peu plus longtemps pour l'avoir sur le dépôt de Kodi, la validation n'est pas instantanée.

**Comment by revanwolf** [comment]
Je viens de tester sous Windows et Android TV avec une installation propre et ça fonctionne.
