### ISSUE TITLE
 Semble ne plus fonctionner (again)

### ISSUE THREAD

**Issue by bateast** [f-lawe/plugin.video.orange.fr#50]
Bonjour,

chez moi, le plugin a arrêté de fonctionner cette semaine. Les logs ne semblent fournir que
> 2024-07-18 10:48:06.676 T:2601    error <general>: CVideoPlayer::OpenInputStream - error opening [pvr://channels/tv/Toutes%20les%20cha%c3%aenes/1@pvr.iptvsimple_1483567100.pvr]

Logs complets joints.

J’ai essayé la version dans le dépôt Kodi, la release github et le pull du dépôt github. Idem.

[kodi.log](https://github.com/user-attachments/files/16280475/kodi.log)

**Comment by f-lawe** [comment]
Hmm.. Je n'arrive pas trop à comprendre d'où ça vient. Tu essayes simplement de regarder TF1 là c'est bien ça ?

**Comment by Lulu5353** [comment]
Fonctionnel sur firestick et tablette Xiaomi pad 6. Par contre avec la même config ne fonctionne pas sur moi box s...

**Comment by f-lawe** [comment]
Je me demande si ça ne vient pas du DRM. C’est quoi Box S ?

**Comment by Lulu5353** [comment]
C'est une box Android TV de la marque Xiaomi

**Comment by bateast** [comment]
> Hmm.. Je n'arrive pas trop à comprendre d'où ça vient. Tu essayes simplement de regarder TF1 là c'est bien ça ?

Exact, aucune chaîne ne fonctionne. L’intégration iptv fonctionne bien pour la sélection des chaînes, mais je ne peux ouvrir aucun _flux_ (?).

Pour info, ma config: raspberry pi4, distrib osmc (debian based).
Ça ne fonctionne pas ni avant ni après mis à jour de Widevine.

Est-ce que tu sais comment je peux extraire plus d’info pour aider (logs, instrumentation du code, tcpdump — mais les adresses sont en https, je risque de ne pas voir grand chose…)

**Comment by f-lawe** [comment]
(ça sera peut-être l'occasion de remonter ça dans les paramètres tiens)

**Comment by bateast** [comment]
> Sur cette intuition de DRM, est-ce que tu peux changer la valeur de retour à la ligne 44 de `utils/kodi.py` par `DRM.PLAYREADY` ?

Nope: [DRM_SCHEMES = {'widevine': 'widevine',    'com.widevine.alpha': 'widevine'}](https://github.com/emilsvennesson/script.module.inputstreamhelper/blob/e5bc154525bcf1dea11138c30f602f441a361d79/lib/inputstreamhelper/config.py#L14)

```com.microsoft.playready```  n’est (plus ?) une option.

```
File "/home/osmc/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 59, in __init__
                                                       raise InputStreamException('UnsupportedDRMScheme')
```

**Comment by f-lawe** [comment]
En effet ça a changé, j'avais à l'époque anticipé le support de plusieurs décodeurs, mais comme Widevine fonctionnait très bien chez moi, je n'étais pas allé plus loin.

Fausse piste donc...

**Comment by f-lawe** [comment]
Je viens de reprendre tes logs : c'est clairement au niveau de InputStream Adaptive que ça coince. Soit il y a des trucs tout simplement non supportés sur ces plateformes (mais quoi ?), soit il faut peut-être adapter les paramètres qu'on lui envoie. 

Si jamais vous vous sentez de faire quelques tests, ça se passe dans le fichier `utils/gui.py`, dans la fonction `create_video_item()` (pour le transfert des paramètres) et dans le fichier `providers/abstract_orange_provider.py`, dans la méthode `_get_stream_info()` (pour la récupération des paramètres depuis Orange).

**Comment by bateast** [comment]
Mis à jour suivant le README de InputStream (le log ```2024-07-23 15:15:52.635 T:25901   debug <CAddonSettings[0@script.module.inputstreamhelper]>: trying to load setting definitions from old format...``` m’a fait tiquer…)

cela semble fonctionner…

Voir la PR.

**Comment by f-lawe** [comment]
Ah, top. Je regarde ça !

**Comment by f-lawe** [comment]
Corrigé en 2.1.4
