### ISSUE TITLE
Catchup fonctionne, plus le direct ni le guide

### ISSUE THREAD

**Issue by bateast** [f-lawe/plugin.video.orange.fr#69]
` info <general>: CAddonMgr::FindAddons: plugin.video.orange.fr v2.3.1 installed`

Catchup fonctionne (parcours des chaînes et contenu, stream d’une émission).

Par contre, **la mise à jour des chaînes ne fonctionne plus** (et je ne peux donc pas tester le stream live des chaînes, puisque je n’ai plus de màj des chaînes).

```
debug <general>: [plugin.video.orange.fr] 3.9.2 (default, Feb 28 2021, 17:03:44)
                                                   [GCC 10.2.1 20210110]
debug <general>: [plugin.video.orange.fr] Initializing addon router
debug <general>: [plugin.video.orange.fr][routing] Dispatching to 'index', args: {}
info <general>: [plugin.video.orange.fr] Display catchup index
debug <general>: [plugin.video.orange.fr] Fetching https://rp-ott-mediation-tv.woopic.com/api-gw/catchup/v4/applications/PC/channels
debug <general>: [plugin.video.orange.fr]  -> 200
debug <general>: DatabaseUtils::GetSortFieldList: unknown field 26
debug <general>: DatabaseUtils::GetSortFieldList: unknown field 31
debug <general>: DatabaseUtils::GetSortFieldList: unknown field 40
debug <general>: DatabaseUtils::GetSortFieldList: unknown field 68
debug <general>: CPythonInvoker(31, /home/osmc/.kodi/addons/plugin.video.orange.fr/resources/addon.py): script successfully run
debug <general>: onExecutionDone(31, /home/osmc/.kodi/addons/plugin.video.orange.fr/resources/addon.py)
```
**3.9.2** ?!
Le téléchargement de _channels_ fonctionne bien.

pas d’erreur dans les logs lors du rafraichissement des chaînes, mais :
```
$ cat ~/.kodi/userdata/addon_data/service.iptv.manager/playlist.m3u8
#EXTM3U
## Orange TV France
```
Et aucune chaîne dans le guide…

**Comment by Enniota** [comment]
any way do get the direct back ?

**Comment by f-lawe** [comment]
Ok, je regarde çaen détail, j'espère ce week-end ! Ce qui est surprenant, c'est que je n'ai pas le souci sur l'installation de mon salon. Est-ce que tu as essayé de revenir à la 2.3.0 ?

Ah, et le 3.9.2, c'est la version de Python, tout simplement !

**Comment by Enniota** [comment]
dans la derniere version rien ne marche ni le direct nis le catchup mais en 2.3.0 le cathup marche mais pas le direct actuellement 
,le direct marchais encore sur la tele qu'il y avait a l'étage jusqu a hier

**Comment by Enniota** [comment]
bonjour des nouvelle ou un moyen de contourné le probleme ?

**Comment by f-lawe** [comment]
Bonjour Enniota,

Ca n'est pas la peine de me relancer au bout de 2/3 jours : je maintiens ce plugin bénévolement, j'ai indiqué que j'avais bien le souci en tête, ensuite je corrige ça quand j'ai le temps.

La bonne nouvelle, c'est que j'ai fait un peu de nettoyage, et que je pense déployer une nouvelle version prochainement. J'espère que ça va régler vos soucis : je n'arrive pas à reproduire le problème chez moi, donc j'ai simplement supposé d'où ça pouvait venir.

**Comment by Enniota** [comment]
Désolé et je verifie ca d'est qu'il est dispo et merci beaucoup pour votre temp

**Comment by f-lawe** [comment]
C'est disponible, en téléchargement depuis Github. J'attends les retours pour publier sur Kodi !
