### ISSUE TITLE
Chaine pas dans l'abonnement

### ISSUE THREAD

**Issue by mysiki** [f-lawe/plugin.video.orange.fr#70]
Bonjour,

Merci pour cette addon, aprés mal pas de test, je n'arrive à rien 🥲 

Je suis sur une airbox orange car ma fibre est ko (intervention du technicien repoussé ...). J'utilise OSMC sur PI. 

J'ai installé l'addon, configuré l'addon avec mes creds orange email@orange.fr / password, puis depuis l'addon, installer IPTVmanager. 

Ensuite "configure iptvsimple automaticlly" puis channels --> refresh channels and guide. 

J'ai bien la vu des programme avec les chaines, mais quand je selectionne une chaine, j'ai un message "cette chaine ne fait pas partie de votre abonnement". 

Est-ce qu'il y a des choses à faire dans IPTV ? Quel logs peuvent étre utiles ? 

Merci 

Edit : info iptv 

config par default, j'ai dans general un chemin local "../../../playlist.m3u8"

Dans iptv fournisseur > nom du fournisseur par default j'ai testé Orange

**Comment by f-lawe** [comment]
Hello

Si tu utilises l'addon depuis une connexion Orange, en théorie, tu n'as pas besoin de mettre tes identifiants. Tu peux essayer sans ?

Si tu es en France métropolitaine, tu as bon sur le fournisseur, sinon il faut effectivement que tu bascules sur Orange Réunion ou Orange Caraïbe. Sachant que pour ces deux là, comme ça fait longtemps que je n'ai pas eu de retour d'utilisateurs de ces départements, je ne suis sûr de rien.

**Comment by Enniota** [comment]
cette erreur n'aparait que sur le catchup de la derniere version pour moi

**Comment by mysiki** [comment]
Je suis bien sur Oragne france. Ma connection est réparé, je n'ai pas testé depuis (donc depuis ma livebox directement)

**Comment by eluisne** [comment]
Bonjour,
Je viens d' installer le plugin dans Kodi et je rencontre exactement le même problème.
J'ai suivi tout la procédure d'installation et de paramétrage avec mes identifiants Orange. Je suis bien connecté à internet depuis une box Orange.

Pourtant, j' obtiens auss systématiquement "cette chaine ne fait pas partie de votre abonnement".

Avez-vous trouvé une solution? Ou une idée?
J' ai fait l'essai sur un RPI + Librelec et avec une TV sous Android.

Merci d'avance

**Comment by f-lawe** [comment]
Je vais déployer prochainement une version qui remet un peu à plat la gestion des DRM , j'espère que c'est ça qui bloque !

Comme expliqué sur une autre discussion, n'arrivant pas à reproduire de problème chez moi (mon instance Kodi qui est installée dans mon salon fonctionne très bien), je suis un peu à tâtons. J'espère que ça fonctionnera !
